[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/redirect/drive"     
  to = "https://drive.google.com/open?id=1HjuUvki3FrK9BKkcequsfCHxNjIVtWbz"
  status = 301

[[redirects]]
  from = "/redirect/istsi"
  to = "https://www.istsi.org/"
  status = 301

[[redirects]]
  from = "/redirect/estagios"
  to = "https://www.istsi.org/"
  status = 301

[[redirects]]
  from = "/redirect/facebook"
  to = "https://www.facebook.com/NEECIST/"
  status = 301

[[redirects]]
  from = "/redirect/jeec"
  to = "https://jeec.ist/"
  status = 301

[[redirects]]
  from = "/redirect/linkedin"
  to = "https://www.linkedin.com/company/2977028/"
  status = 301

[[redirects]]
  from = "/redirect/maps"
  to = "https://encrypted.google.com/maps/place/NEECIST"
  status = 301

[[redirects]]
  from = "/redirect/salas"
  to = "https://fenix.tecnico.ulisboa.pt/conteudos-publicos/pesquisa-de-espacos"
  status = 301

[[redirects]]
  from = "/redirect/twitter"
  to = "https://twitter.com/NEECIST/"
  status = 301

[[redirects]]
  from = "/redirect/youtube"
  to = "https://www.youtube.com/user/NEECIST/"
  status = 301

[[redirects]]
  from = "/redirect/instagram"
  to = "https://www.instagram.com/neecist/"
  status = 301



